name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: artemvoronov/buildozer-action@v1
      with:
        command: android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
