name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Buildozer (Docker)
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/home/user/hostcwd \
          kivy/buildozer \
          buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
