name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Install Android SDK tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip cmdtools.zip
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          mv latest/cmdline-tools latest/tools
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$PATH
          yes | $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set buildozer build tools version
        run: |
          sed -i 's/^android.build_tools_version =.*$/android.build_tools_version = 34.0.0/' buildozer.spec

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          buildozer android debug
          ls -R .

      - name: Find APK
        run: |
          echo "APK files found:"
          find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: ./**/*.apk
